name: 'Checkout repository'
description: 'Checks out the repository code'

runs:
    using: 'composite'
    steps:
        - name: Checkout code
          uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
