reviews:
  # High-level instructions for all reviews
  profile: "strict" 
  request_changes_workflow: false
  
  # Specific prompts for the AI
  instructions: |
    - Do not make suggestions when we use x.x for a version placeholder. This is intentionally set to x.x as part of our release process.