dist: trusty
language: php

sudo: false

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=master WP_MULTISITE=1 SCRIPT_DEBUG=1
    - php: nightly
      env: WP_VERSION=master
  allow_failures:
    - php: nightly
    
before_script:
- |
  # Remove Xdebug for a huge performance increase:
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    phpenv config-rm xdebug.ini
  else
    echo "xdebug.ini does not exist"
  fi
- |
  # Install the specified version of PHPUnit depending on the PHP version:
  echo "Using PHPUnit 7.x"
  travis_retry composer require --ignore-platform-reqs "phpunit/phpunit:^7"
- ./vendor/bin/phpunit --version
- mysql --version
- PLUGIN_SLUG=$(basename $(pwd))
- export WP_DEVELOP_DIR=/tmp/wordpress/
- git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
- cd ..
- cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/formidable"
- cd /tmp/wordpress/
- cp wp-tests-config-sample.php wp-tests-config.php
- sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
- sed -i "s/yourusernamehere/travis/" wp-tests-config.php
- sed -i "s/yourpasswordhere//" wp-tests-config.php
- mysql -u root -e "CREATE DATABASE wordpress_tests;"
- cd "/tmp/wordpress/src/wp-content/plugins/formidable"
- phpenv rehash

script:
- if [[ "$SCRIPT_DUBUG" == "1" ]]; then php -r "define('SCRIPT_DUBUG', true);"; fi
- if [[ "$SCRIPT_DUBUG" == "0" ]]; then php -r "define('SCRIPT_DUBUG', false);"; fi
- |
  ./vendor/bin/phpunit --group=ajax -c phpunit.xml
  ./vendor/bin/phpunit --group=entries -c phpunit.xml
  ./vendor/bin/phpunit --group=styles -c phpunit.xml
  ./vendor/bin/phpunit --exclude-group=ajax,entries,styles -c phpunit.xml
