name: 'Set up Node and dependencies'
description: 'Installs Node.js and npm packages with caching for faster builds'
inputs:
    node-version:
        description: 'Node.js version (defaults to .nvmrc if not specified)'
        required: false
        type: string

runs:
    using: 'composite'
    steps:
        - name: Set up Node.js
          uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
          with:
              node-version-file: ${{ inputs.node-version == '' && '.nvmrc' || '' }}
              node-version: ${{ inputs.node-version }}
              check-latest: true
              cache: npm

        - name: Detect Node version
          id: node-version
          run: |
              echo "NODE_VERSION=$(node -v)" >> "$GITHUB_OUTPUT"
          shell: bash

        - name: Restore cached dependencies
          id: cache-node_modules
          uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
          with:
              path: '**/node_modules'
              key: node_modules-${{ runner.os }}-${{ runner.arch }}-${{ steps.node-version.outputs.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

        - name: Install dependencies
          if: ${{ steps.cache-node_modules.outputs.cache-hit != 'true' }}
          run: npm ci
          shell: bash

        - name: Save npm logs on failure
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
          if: failure()
          with:
              name: npm-logs
              path: ~/.npm/_logs
