on: [push]

name: PHPStan Code Analysis
jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    steps:
      - name: "📥 Fetching Repository Contents"
        uses: actions/checkout@v4.1.1

      - name: "💽  Installing PHP, Composer, CS2PR"
        uses: shivammathur/setup-php@2.30.2
        with:
          php-version: 8.1
          coverage: none
          ini-values: display_errors = on, error_reporting = E_ALL
          tools: composer

      - name: "💽  Installing Composer Packages"
        run: composer install

      - name: "🧪 Test"
        run: vendor/bin/phpstan analyze ./ --memory-limit=2G
