name: Stylelint

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, labeled, synchronize]

jobs:
  runStylelintInspection:
    if: contains(github.event.pull_request.labels.*.name, 'run analysis')
    name: Run Stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Remove package files for faster install
        run: rm -f package.json package-lock.json

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Install Stylelint
        run: npm install stylelint @wordpress/stylelint-config --no-package-lock

      - name: Run Stylelint
        run: npx stylelint "**/*.{css,scss}"
